CREATE TABLE IF NOT EXISTS posts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(500) NOT NULL DEFAULT '',
  slug VARCHAR(200) NOT NULL DEFAULT '',
  excerpt TEXT,
  content LONGTEXT,
  featured_image VARCHAR(500) NOT NULL DEFAULT '',
  tags_json JSON,
  meta_title VARCHAR(500) NOT NULL DEFAULT '',
  meta_description TEXT,
  status ENUM('draft','published') NOT NULL DEFAULT 'draft',
  author VARCHAR(200) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY idx_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
