CREATE TABLE IF NOT EXISTS analytics_events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  visitor_id VARCHAR(64) NOT NULL DEFAULT '',
  event_type ENUM('pageview','click','scroll') NOT NULL DEFAULT 'pageview',
  page_url VARCHAR(500) NOT NULL DEFAULT '',
  element_target VARCHAR(200) NOT NULL DEFAULT '',
  element_text VARCHAR(200) NOT NULL DEFAULT '',
  latitude DOUBLE DEFAULT NULL,
  longitude DOUBLE DEFAULT NULL,
  location_source ENUM('ip','gps') DEFAULT NULL,
  city VARCHAR(100) NOT NULL DEFAULT '',
  region VARCHAR(100) NOT NULL DEFAULT '',
  country VARCHAR(50) NOT NULL DEFAULT '',
  device_type ENUM('desktop','mobile','tablet','unknown') NOT NULL DEFAULT 'unknown',
  browser VARCHAR(50) NOT NULL DEFAULT '',
  os VARCHAR(50) NOT NULL DEFAULT '',
  screen_width INT DEFAULT NULL,
  screen_height INT DEFAULT NULL,
  user_agent VARCHAR(500) NOT NULL DEFAULT '',
  ip_address VARCHAR(45) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_visitor (visitor_id),
  INDEX idx_event_type (event_type),
  INDEX idx_created (created_at),
  INDEX idx_page_url (page_url(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS analytics_visitors (
  id INT AUTO_INCREMENT PRIMARY KEY,
  visitor_id VARCHAR(64) NOT NULL DEFAULT '',
  first_seen DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  total_visits INT NOT NULL DEFAULT 0,
  total_clicks INT NOT NULL DEFAULT 0,
  city VARCHAR(100) NOT NULL DEFAULT '',
  region VARCHAR(100) NOT NULL DEFAULT '',
  country VARCHAR(50) NOT NULL DEFAULT '',
  device_type ENUM('desktop','mobile','tablet','unknown') NOT NULL DEFAULT 'unknown',
  browser VARCHAR(50) NOT NULL DEFAULT '',
  os VARCHAR(50) NOT NULL DEFAULT '',
  latitude DOUBLE DEFAULT NULL,
  longitude DOUBLE DEFAULT NULL,
  UNIQUE KEY idx_visitor_id (visitor_id),
  INDEX idx_last_seen (last_seen),
  INDEX idx_city (city)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
